local_backend: falsebackend:
  branch: main
  name: github
  repo: Ediieey/velnora
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Event Title", name: "title", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - { label: "Event Image", name: "image", widget: "image" }

      - { label: "Description", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Image", name: "image", widget: "image" }