backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "string"

      - label: "Cover Image"
        name: "image"
        widget: "image"

      - label: "Gallery"
        name: "gallery"
        widget: "list"
        field:
          label: "Gallery Image"
          name: "gallery_image"
          widget: "image"

      - label: "Description"
        name: "body"
        widget: "markdown"

  - name: "memories"
    label: "Memories"
    folder: "content/memories"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Location"
        name: "location"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "string"

      - label: "Cover Image"
        name: "image"
        widget: "image"

      - label: "Gallery"
        name: "gallery"
        widget: "list"
        field:
          label: "Gallery Image"
          name: "gallery_image"
          widget: "image"

      - label: "Description"
        name: "body"
        widget: "markdown"

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Image"
        name: "image"
        widget: "image"